drop table comentario;
drop table jogo;
drop table usuario;

drop sequence usuario_sequence;
drop sequence jogo_sequence;
drop sequence comentario_sequence;

CREATE TABLE USUARIO (
	USUARIO_ID NUMERIC(4) NOT NULL,
	EMAIL VARCHAR(50) NULL, 
	NOME VARCHAR(50) NULL,
	CPF NUMERIC(11) NULL,
	SENHA VARCHAR(30) NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (USUARIO_ID)
);

CREATE TABLE JOGO (
	JOGO_ID NUMBER(4) NULL,
	USUARIO_ID NUMBER(4) NOT NULL,
	TITULO VARCHAR(80) NULL,
	LIKES NUMBER(3) NULL,
	GENERO VARCHAR(20) NULL,
	AVALIACAO NUMBER(2,1) NULL,
	CONSTRAINT PK_JOGO PRIMARY KEY (JOGO_ID),
	CONSTRAINT FK_USUARIO_JOGO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);

CREATE TABLE COMENTARIO (
	COMENTARIO_ID NUMBER(4) NOT NULL,
	JOGO_ID NUMBER(4) NOT NULL,
	USUARIO_ID NUMBER(4) NULL,
	TEXTO VARCHAR(250) NULL,
	DATA_POSTAGEM VARCHAR(21) NULL,
	CONSTRAINT PK_COMENTARIO PRIMARY KEY (COMENTARIO_ID),
	CONSTRAINT FK_JOGO_COMENTARIO FOREIGN KEY (JOGO_ID) REFERENCES JOGO (JOGO_ID),
	CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID)
);

CREATE SEQUENCE usuario_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE jogo_sequence START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE comentario_sequence START WITH 1 INCREMENT BY 1;

commit;