CREATE OR REPLACE TRIGGER TRG_DATA_COMENTARIO
BEFORE INSERT ON COMENTARIO
FOR EACH ROW
DECLARE
	DATA_HORA VARCHAR(21);
BEGIN
	SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') INTO DATA_HORA FROM DUAL;
	
	:NEW.DATA_POSTAGEM := DATA_HORA;
END;
/