/*TRIGGER DE AUDITORIA NA TABELA PRODUTO*/
CREATE SEQUENCE IDPRODUTO_HISTORICO_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER PRODUTO_TRG_PI 
AFTER UPDATE OR INSERT OR DELETE OF PRECO ON PRODUTO
FOR EACH ROW 
DECLARE
	ACAO VARCHAR(10);
	IP VARCHAR(20);
	DATA_HORA VARCHAR(21);
BEGIN
	
	SELECT SYS_CONTEXT('USERENV', 'IP_ADDRESS') INTO IP FROM DUAL;
	SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') INTO DATA_HORA FROM DUAL;
	
	IF INSERTING THEN 
		ACAO := 'INSERT';
		INSERT INTO HISTORICO_PRODUTO
			(IDPRODUTO_HISTORICO, IDPRODUTO, PRECO_ANTIGO, TIPO_ACAO, USUARIO, DATA_ACAO, IP_USUARIO) 
			VALUES 
			(IDPRODUTO_HISTORICO_SEQ.NEXTVAL, :NEW.ID, :OLD.PRECO, ACAO, USER, DATA_HORA, IP);
		
	ELSIF UPDATING OR DELETING THEN
		
		IF UPDATING THEN
			ACAO := 'UPDATE';
		ELSE
			ACAO := 'DELETE';	
			
		END IF;
		
		INSERT INTO HISTORICO_PRODUTO
		(IDPRODUTO_HISTORICO, IDPRODUTO, PRECO_ANTIGO, TIPO_ACAO, USUARIO, DATA_ACAO, IP_USUARIO) 
		VALUES 
		(IDPRODUTO_HISTORICO_SEQ.NEXTVAL, :OLD.ID, :OLD.PRECO, ACAO, USER, DATA_HORA, IP);
	END IF;
END;
/

CREATE TABLE HISTORICO_PRODUTO (
	IDPRODUTO_HISTORICO NUMERIC(4) NOT NULL,
	IDPRODUTO NUMERIC(4) NOT NULL,
	PRECO_ANTIGO NUMERIC(10,2) NULL,
	TIPO_ACAO VARCHAR(10) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	DATA_ACAO VARCHAR(21) NOT NULL,
	IP_USUARIO VARCHAR(20) NOT NULL,
	CONSTRAINT IDPRODUTO_HISTORICO PRIMARY KEY (IDPRODUTO_HISTORICO)
);